---
title: "ARM Chapter 11 Exercises"
author: "Sam Voisin"
date: "July 23, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(rjags)

set.seed(1)

```

## Chapter 11: Multilevel Structures

### Exercises

#### 1)

```{r}

rodents <- read.table("http://www.stat.columbia.edu/~gelman/arm/examples/rodents/apt.dat")
rodents <- na.omit(rodents)
str(rodents)

```


```{r}

dist <- read.table("http://www.stat.columbia.edu/~gelman/arm/examples/rodents/dist.dat")
str(dist)

```

Fitting the multilevel model

```{r}

# define the model in jags
mod_string <- "model {
  # individual level/ first level
  for (i in 1:length(y)) {

    y[i] ~ dbern(p[i])

    logit(p[i]) <- b[1] * defects[i] +
                   b[2] * poor[i] +
                   alpha[dist[i]]

  }

  # district level/ group level/ second level
  # variable intercepts for district effects
  for (j in 1:55) {
    alpha[j] ~ dnorm(mu_alpha[j], prec_alpha)

    mu_alpha[j] <- gamma[1] * dist_defects[j] + gamma[2] * dist_poor[j]

  }

  # priors for coefficients
  for (j in 1:2) {
    b[j] ~ dnorm(0.0, prec_beta)
  }

  for (j in 1:2) {
    gamma[j] ~ dnorm(0.0, prec_gamma)
  }

  # priors for precision
  prec_alpha ~ dgamma(0.01, 0.01)
  prec_gamma ~ dgamma(0.01, 0.01)
  prec_beta ~ dgamma(0.01, 0.01)

}

"

```



```{r}

# set up the model #

# data
data_reg_jags = list(y = rodents$y,
                     defects = rodents$defects,
                     poor = rodents$poor,
                     dist = rodents$dist,
                     dist_defects = dist$dist.defects,
                     dist_poor = dist$dist.poor)

# parameters
params = c("b", "gamma", "alpha", "prec_alpha", "prec_gamma", "prec_beta")

# initial values
inits <- function() {
  inits <- list(alpha = rnorm(55, 0.0, 1.0),
                b = rnorm(2, 0.0, 1.0),
                gamma = rnorm(2, 0.0, 1.0),
                prec_alpha = rgamma(1, shape = 0.01, rate =  0.01),
                prec_gamma = rgamma(1, shape = 0.01, rate =  0.01),
                prec_beta = rgamma(1, shape = 0.01, rate =  0.01))
}

# compile model
apts_model <- jags.model(file = textConnection(mod_string),
                         data = data_reg_jags,
                         inits = inits,
                         n.chains = 3)

```

Do 2000 iterations of burn-in:

```{r}

update(apts_model, 2000)

```

Perform posterior sampling:

```{r}

apts_model_sim <- coda.samples(model = apts_model,
                               variable.names = params,
                               n.iter = 10000)

comb_chains_apts <- as.mcmc(do.call(rbind, apts_model_sim))
  
```

Convergence diagnostics:

```{r}

summary(apts_model_sim)
effectiveSize(comb_chains_apts)
autocorr.diag(apts_model_sim)

```


```{r}

# take every 5th iteration
thin5_comb_chains <- comb_chains_apts[seq(1, 30000, by = 5), ]

# gamma 1
autocorr.diag(comb_chains_apts[, 58])
autocorr.plot(comb_chains_apts[, 58])

# take every 5th iteration
thin5_comb_chains <- as.mcmc(comb_chains_apts[seq(1, 30000, by = 5), ])

# auto correlation significantly reduced
autocorr.diag(thin5_comb_chains[, 58])
autocorr.plot(thin5_comb_chains[, 58])

```


```{r}

plot(thin5_comb_chains)

```

Effective sample sizes:

```{r}

tibble(
  variable = names(effectiveSize(comb_chains_apts)),
  eff_size_pre_thin = effectiveSize(comb_chains_apts),
  eff_size_post_thin = effectiveSize(thin5_comb_chains)
) %>% 
  mutate(change = eff_size_pre_thin - eff_size_post_thin,
         change_percent = change / eff_size_pre_thin)

```

Testing model performance:

```{r}

# sigmoid function
sigmoid <- function(x) {
  res <- 1 / (1 + exp(-x))
  return(res)
}

```


```{r}

# get mean/ MAP estimates for coeficients
param_means <- summary(thin5_comb_chains)$statistics[, 1]
alphas <- param_means[1:55]
gammas <- param_means[58:59]
betas <- param_means[56:57]

# make predictions
yhats <- c()
for (i in 1:nrow(rodents)) {
  logit_hat_i <- betas[1] * rodents$defects[i] +
                 betas[2] * rodents$poor[i] +
                 alphas[rodents$dist[i]]
  
  yhats <- c(yhats, sigmoid(logit_hat_i))
  
}

```


```{r}

library(ROCR)
preds_obj <- prediction(predictions = yhats, labels = rodents$y)
perf_obj <- performance(prediction.obj = preds_obj, "tpr", "fpr")
plot(perf_obj)

```

```{r}

perf_obj <- performance(prediction.obj = preds_obj, "acc")
plot(perf_obj)

```

```{r}

table(factor(rodents$y)) / nrow(rodents)

```


Posterior predictive checks:

```{r}

# sample from priors


```

